language: python
cache: pip
python:
  - "3.7"
# command to install dependencies
install:
  - pip3 install --upgrade setuptools
  - pip3 install --upgrade -r requirements.txt
  - pip3 install --upgrade .
  - pip3 install --upgrade tox-travis
# command to run tests
script: travis_wait 60 tox
after_success: coveralls
